# Regresión lineal múltiple

### Regresión lineal múltiple

El modelo de regresión lineal múltiple es una generalización del modelo de regresión lineal simple.

\bigpause

En este modelo consideramos un conjunto de variables independientes $X_{0\, 1}, X_{0\, 2}, \ldots, X_{0\, p}$ y una variable dependiente $Y_{0}$, las cuales satisfacen una relación de la forma:
$$
Y_{0} = b_{0} + b_{1}X_{0\, 1} + b_{2}X_{0\, 2} + \cdots + b_{p}X_{0\, p} + \epsilon_{0}
$$
donde $\epsilon_{0} \sim \mathcal{N}(0, \sigma^{2})$.

\bigpause

Notemos que este modelo depende de los parámetros $b_{0}, b_{1}, \ldots, b_{p}$ y $\sigma^{2}$.

## Ajuste del modelo de regresión lineal múltiple

### Ajuste del modelo de regresión lineal múltiple

Para ajustar un modelo de regresión lineal múltiple, empezaremos por introducir una matriz
$$
X = \begin{bmatrix}
X_{11} & X_{12} & \ldots & X_{1p} \\
X_{21} & X_{22} & \ldots & X_{2p} \\
\vdots & \vdots & \ddots & \vdots \\
X_{n1} & X_{n2} & \ldots & X_{np}
\end{bmatrix}
$$
que contiene las variables independientes para $n$ observaciones, y un vector aleatorio
$$
Y = \begin{bmatrix}
Y_{1} \\
Y_{2} \\
\vdots \\
Y_{n}
\end{bmatrix}
$$
que contiene las variables dependientes para las mismas $n$ observaciones.

###

En este contexto, estas variables satisfacen una relación de la forma
$$
Y = Xb + \epsilon
$$
donde
$$
b = \begin{bmatrix}
b_{0} \\
b_{1} \\
\vdots \\
b_{p}
\end{bmatrix}
$$
es el vector de parámetros y
$$
\epsilon = \begin{bmatrix}
\epsilon_{1} \\
\epsilon_{2} \\
\vdots \\
\epsilon_{n}
\end{bmatrix}
$$
es el vector de errores aleatorios, que asumimos que sigue una distribución normal
$$
\epsilon \sim \mathcal{N}(0, \sigma^{2}I_{n})
$$	

###

Supongamos ahora que tenemos un conjunto de datos observados 
$$
x = \begin{bmatrix}
x_{11} & x_{12} & \ldots & x_{1p} \\
x_{21} & x_{22} & \ldots & x_{2p} \\
\vdots & \vdots & \ddots & \vdots \\
x_{n1} & x_{n2} & \ldots & x_{np}
\end{bmatrix} 
$$
para las variables independientes y
$$
y = \begin{bmatrix}
y_{1} \\
y_{2} \\
\vdots \\
y_{n}
\end{bmatrix}
$$
para la variable dependiente.

###

De manera similar al caso de regresión lineal simple, podemos definir la matriz de diseño asociada a estos datos como
$$
\Phi = \begin{bmatrix}
1 & x_{11} & x_{12} & \ldots & x_{1p} \\
1 & x_{21} & x_{22} & \ldots & x_{2p} \\
\vdots & \vdots & \vdots & \ddots & \vdots \\
1 & x_{n1} & x_{n2} & \ldots & x_{np}
\end{bmatrix}
$$

### 
	
Calculamos ahora la matrix de coeficientes
$$
D^{2} = (\Phi^{T}\Phi)^{-1}
$$

\pause

la matriz de estimadores
$$
A = D^{2} \Phi^{T}
$$

\pause

y la matriz sombrero
$$
H = \Phi A
$$

###

Con estas matrices podemos calcular ahora los estimadores puntuales
$$
\hat{\beta} = Ay 
$$

\pause

y los valores ajustados
$$
\hat{y} = H y
$$

###

Para calcular los intervalos de confianza para los parámetros, necesitamos calcular la suma de errores al cuadrado
$$
\text{sse} = \| y - \hat{y} \|^{2} = \| (I - H)y \|^{2}
$$

\pause

Con este valor a la mano, podemos calcular el estimador de la varianza de los errores
$$
\hat{\sigma}^{2} = \frac{\text{sse}}{n - p - 1}
$$

###

Ahora, dado un nivel de significancia $\alpha$, podemos calcular los intervalos de confianza para los parámetros $b_{0}, b_{1}, \ldots, b_{p}$ como
$$
\hat{\beta}_{j} \pm t_{n - p - 1, 1 - \alpha/2} \sqrt{\hat{\sigma}^{2} d_{jj}^{2}}
$$
donde $d_{jj}^{2}$ es la entrada $(j, j)$ de la matriz $D^{2}$ y $t_{n - p - 1, 1 - \alpha/2}$ es el cuantil $1 - \alpha/2$ de la distribución $t$ de Student con $n - p - 1$ grados de libertad.

###

Supongamos ahora que tenemos un nuevo vector de datos $x_{0} = (x_{01}, x_{02}, \ldots, x_{0p})$ para las variables independientes y queremos calcular una banda de confianza para la variable dependiente correspondiente.

\pause

Para ello, calculamos el valor ajustado 
$$
\hat{y}_{0} = b_{0} + b_{1}x_{01} + b_{2}x_{02} + \ldots + b_{p}x_{0p} = \phi_{0} \hat{\beta}
$$
donde
$$
\phi_{0} = \begin{bmatrix}
1 & x_{01} & x_{02} & \ldots & x_{0p}
\end{bmatrix}
$$
es el vector de diseño asociado a los datos $x_{0}$.

###

Con este valor a la mano, podemos calcular la banda de confianza para la predicción de la variable dependiente correspondiente como
$$
\hat{y}_{0} \pm t_{n - p - 1, 1 - \alpha/2} \sqrt{\hat{\sigma}^{2} (\phi_{0} D^{2} \phi_{0}^{T})}
$$

\pause

La banda de predicción para la variable dependiente está dada por la expresión
$$
\hat{y}_{0} \pm t_{n - p - 1, 1 - \alpha/2} \sqrt{\hat{\sigma}^{2} (1 + \phi_{0} D^{2} \phi_{0}^{T})}
$$


## Evaluación del modelo ajustado 

### Máxima verosimilitud 

Dado un conjunto de datos 
$$
x = \begin{bmatrix}
x_{11} & x_{12} & \ldots & x_{1p} \\
x_{21} & x_{22} & \ldots & x_{2p} \\
\vdots & \vdots & \ddots & \vdots \\
x_{n1} & x_{n2} & \ldots & x_{np}
\end{bmatrix} \qquad 
y = \begin{bmatrix}
y_{1} \\
y_{2} \\
\vdots \\
y_{n}
\end{bmatrix}
$$
La función de verosimilitud del modelo de regresión lineal es una función que nos da una medida de la consistencia entre los datos dados y los parámetros considerados en el modelo.

###

En nuestro caso, la función de verosimilitud es:
$$
L(b_{0}, b_{1}, \ldots, b_{p}, \sigma^{2} | x, y) = \prod_{i=1}^{n} \frac{1}{\sqrt{2\pi\sigma^{2}}} \exp\left( -\frac{(y_{i} - (b_{0} + b_{1}x_{i1} + \ldots + b_{p}x_{ip}))^{2}}{2\sigma^{2}} \right)
$$
que corresponde a la función de densidad del modelo considerado con los parámetros indicados y los datos observados.

\bigpause

Notemos que en esta función estamos considerando los datos $x$ e $y$ como fijos, y los parámetros $b_{0}, b_{1}, \ldots, b_{p}$ y $\sigma^{2}$ como variables.

\bigpause

Nuestro siguiente objetivo será encontrar los valores de estos parámetros que maximicen la función de verosimilitud, es decir, que hagan que los datos observados sean lo más consistentes posible con el modelo.

###

Empezaremos por considerar la log-verosimilitud, que es simplemente el logaritmo natural de la función de verosimilitud:
\begin{align}
\ell(b_{0}, b_{1}, \ldots, b_{p}, \sigma^{2} | x, y) = & \log L(b_{0}, b_{1}, \ldots, b_{p}, \sigma^{2} | x, y) \nonumber \\
= & -\frac{n}{2} \log(2\pi\sigma^{2}) - \frac{1}{2\sigma^{2}} \sum_{i=1}^{n} (y_{i} - (b_{0} + b_{1}x_{i1} + \ldots + b_{p}x_{ip}))^{2} \label{eq:logverosimilitud}
\end{align}

\pause

Notemos que maximizar la función de verosimilitud es equivalente a maximizar la log-verosimilitud, ya que el logaritmo es una función monótonamente creciente.

###

Para encontrar los valores de 
$$
b = \begin{bmatrix} 
b_{0} \\
b_{1} \\ 
\vdots \\
b_{p}
\end{bmatrix}
$$
que maximicen la log-verosimilitud, nos basta con minimizar la expresión:
$$
 \sum_{i=1}^{n} (y_{i} - (b_{0} + b_{1}x_{i1} + \ldots + b_{p}x_{ip}))^{2}
$$ 

###

Se sigue que podemos utilizar el método de los mínimos cuadrados para encontrar los valores de los parámetros que buscamos: 
$$
b_{\text{MLE}} = \hat{\beta} = (\Phi^{T}\Phi)^{-1}\Phi^{T}y 
$$
donde 
$$
\Phi = \begin{bmatrix} 
1 & x_{11} & x_{12} & \ldots & x_{1p} \\ 
1 & x_{21} & x_{22} & \ldots & x_{2p} \\ 
\vdots & \vdots & \vdots & \ddots & \vdots \\
1 & x_{n1} & x_{n2} & \ldots & x_{np}
\end{bmatrix}
$$
es la matriz de diseño asociada a nuestros datos.

###

Finalmente, para encontrar el valor de $\sigma^{2}$ que maximice la log-verosimilitud, podemos derivar la expression de la log-verosimilitud con respecto a $\sigma^{2}$ y encontrar el valor que hace que la derivada sea cero.

\bigpause

Esto nos lleva a la siguiente expresión para el estimador de máxima verosimilitud de $\sigma^{2}$:
$$
\sigma^{2}_{\text{MLE}} = \frac{1}{n} \sum_{i=1}^{n} \big[y_{i} - (\hat{\beta}_{0} + \hat{\beta}_{1}x_{i1} + \ldots + \hat{\beta}_{p}x_{ip})\big]^{2} = \frac{\text{sse}}{n}
$$ 


###

Desde este punto de vista, hemos obtenido una función que a cada conjunto de datos le asigna su máxima verosimilitud o, más precisamente, su máxima log-verosimilitud bajo el modelo de regresión lineal.

\bigpause

Notemos que este valor está dado de manera explícita por:
$$
\ell(\hat{\beta}, \sigma^{2}_{\text{MLE}} | x, y) = -\frac{n}{2} \log(2\pi) - \frac{n}{2} \log\left( \frac{\text{sse}}{n} \right) - \frac{n}{2}
$$

\pause

\begin{observacion}
Notemos que el hecho de que el ajuste por mínimos cuadrados coincida con el ajuste por máxima verosimilitud es una consecuencia de la suposición de que los errores aleatorios $\epsilon_{i}$ siguen una distribución normal. En particular, si los errores no siguieran una distribución normal, entonces el ajuste por máxima verosimilitud podría no coincidir con el ajuste por mínimos cuadrados.
\end{observacion}

### Significancia del modelo y de los parámetros

Nos gustaría ahora poder afirmar que los valores de la variables independientes $X_{0\, 1}$, $X_{0\, 2}$, $\ldots$, $X_{0\, p}$ tienen un efecto significativo en la variable dependiente $Y_{0}$.

\bigpause

En particular, nos gustaría poder afirmar que al menos uno de los parámetros $b_{1}, b_{2}, \ldots, b_{p}$ es significativamente distinto de cero.

###

De acuerdo al formalismo de las pruebas de hipótesis, lo que debemos hacer ahora es plantear una hipótesis nula que dice que todos los parámetros son iguales a zero y tratar de reunir una evidencia estadísticamente significativa que nos permita rechazar esta hipótesis.

###

Con estas consideraciones en mente, consideraremos la \emph{suma total de cuadrados} (SST, por sus siglas en inglés) definida como: 
$$
SST = \sum_{i=1}^{n} (Y_{i} - \bar{Y})^{2} = \| Y - \bar{Y}\mathbf{1} \|^{2} 
$$
donde 
$$
\bar{Y} = \frac{1}{n} \sum_{i=1}^{n} Y_{i} 
$$
es la media muestral de la variable dependiente y $\mathbf{1}$ es el vector columna de $n$ entradas iguales a uno.

###

La SST se puede interpretar como una variable aleatoria que mide la variabilidad total de los datos asociados a una observación y se puede descomponer como 
$$
SST = SSR + SSE 
$$ 
donde 
$$ 
SSE = \sum_{i=1}^{n} (Y_{i} - \hat{Y}_{i})^{2} = \| Y - \hat{Y} \|^{2} 
$$ 
es la suma de los errores al cuadrado que habíamos considerado anteriormente y que corresponde a la variabilidad de los datos que no es explicada por el modelo, y 
$$ 
SSR = \sum_{i=1}^{n} (\hat{Y}_{i} - \bar{Y})^{2} = \| \hat{Y} - \bar{Y}\mathbf{1} \|^{2}
$$ 
es la \emph{suma de cuadrados de la regresión} y corresponde a la variabilidad de los datos que nuestro modelo explica.

###

Notemos que
$$
\frac{SSE}{\sigma^{2}}  \sim \chi^{2}_{n - p - 1} 
$$ 

\pause

Por otro lado, bajo la hipótesis nula de que todos los parámetros $b_{1}, b_{2}, \ldots, b_{p}$ son iguales a cero, se puede demostrar que 
$$ 
\frac{SSR}{\sigma^{2}} \sim \chi^{2}_{p} 
$$ 
y que $SSE$ y $SSR$ son independientes. 

\bigpause

Con estas consideraciones en mente, podemos definir el estadístico de prueba 
$$ 
F = \frac{SSR / p}{SSE / (n - p - 1)} \sim F_{p, n - p - 1} 
$$ 
donde $F_{p, n - p - 1}$ es la distribución $F$ de Fisher con $p$ y $n - p - 1$ grados de libertad.

###

Notemos que valores grandes de $F$ indican que la variabilidad explicada por el modelo es grande en comparación con la variabilidad no explicada, lo cual constituye evidencia en contra de la hipótesis nula.

\bigpause

Por lo tanto, para nuestra prueba de hipótesis, usaremos una regla de una cola por la derecha. En particular, si $f$ es el valor de nuestro estadístico $F$ evaluado en una observación $Y=y$, entonces el $p$-valor de la prueba es 
$$
p_{F} = P_{F}(F \geq f)
$$ 

\pause

Si $p < \alpha$, para algún nivel de significancia $\alpha$ preestablecido, entonces rechazamos la hipótesis nula y concluimos que al menos uno de los parámetros $b_{1}, b_{2}, \ldots, b_{p}$ es significativamente diferente de cero.

### Resumen para evaluar la significancia del modelo

\begin{enumerate} 
\item \pause Plantear la hipótesis nula y la hipótesis alternativa: 
$$
\begin{array}{rl}
H_{0}:  & \text{Todos los parámetros son iguales a cero, es decir $b_{1} = b_{2} = \cdots = b_{p} = 0$} \\
H_{1}:  & \text{Al menos uno de los parámetros $b_{1}$, $b_{2}$, \ldots, $b_{p}$ es diferente de cero.}
\end{array}
$$
\item \pause Calcular el estadístico de prueba 
$$ 
F = \frac{SSR / p}{SSE / (n - p - 1)} 
$$ 
\item \pause Calcular el $p$-valor de la prueba 
$$ 
p_{F} = P_{F_{p, n - p - 1}}(F \geq f) 
$$ 
\item \pause Si $p_{F} < \alpha$, entonces rechazamos la hipótesis nula y concluimos que al menos uno de los parámetros $b_{1}, b_{2}, \ldots, b_{p}$ es significativamente diferente de cero. 
\end{enumerate}
